# Generated by Django 3.2.9 on 2023-08-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='df_model',
            old_name='product_Category',
            new_name='product_category',
        ),
    ]
